# This is a basic workflow to help you get started with Actions

name: Build Vue Project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [2.7, 3.6, 3.8]

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Cloning the repo
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # - name: Setup Node.js environment
      - name: Setting up node env v14
        uses: actions/setup-node@v2.5.1
        with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: '14'

      - name: Install dependencies
        run: yarn

      - name: Build Project
        run: yarn build

      # - name: Save build artifacts
      - name: Saving the build artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{matrix.os}}-${{matrix.python}}-build
          path: dist
